mutation UpdateMyAdminPassword($oldPassword: String!, $newPassword: String!) {
  updateMyAdminPassword(oldPassword: $oldPassword, newPassword: $newPassword)
}



mutation UpdateMyAdminProfile($userInput: UpdateMyAdminProfileInput!) {
  updateMyAdminProfile(userInput: $userInput)
}

mutation EnableEmailNotification($userId: String!) {
  enableEmailNotification(userId: $userId)
}

mutation DisableEmailNotification($userId: String!) {
  disableEmailNotification(userId: $userId)
}

mutation LockAdmin($userId: String!) {
  lockAdmin(userId: $userId)
}
