mutation AddCredit($creditInput: CreditInput!, $organizationId: ID!) {
  addCredit(creditInput: $creditInput, organizationId: $organizationId)
  {
    id
  }
}

query FetchPaginatedOperations($queryFilter: QueryDataConfigInput, $organizationId: ID!, 
								$metricsInput: OperationsMetricsInput) {
	fetchPaginatedOperations(queryFilter: $queryFilter, organizationId: $organizationId, metricsInput: $metricsInput) {
		pagination {
			totalItems
			pageCount
			currentPage
			pageSize
		}
		results {
			id
			amount
			createdAt
			type
			matricule
			collaborator
			numeroOperation
		}
	}
}

query FetchOperations($organizationId: ID!) {
  fetchOperations(organizationId: $organizationId) {
    matricule
    collaborator
    date
    operation
    numeroOperation
    montant
  }
}