query FetchDemandesMetrics($metricsInput: DemandesMetricsInput!) {
  fetchDemandesMetrics(metricsInput: $metricsInput) {
    remaining {
      y: amount
      x: date
    }
    total {
      y: amount
      x: date
    }
  }
}

query FetchOperationsMetrics($metricsInput: DemandesMetricsInput!, $organizationId: ID!) {
  fetchOperationsMetrics(metricsInput: $metricsInput, organizationId: $organizationId) {
    credit {
      y: amount
      x: date
    }
    debit {
      y: amount
      x: date
    }
  }
}

