query FetchMyBulkPayments {
  fetchMyBulkPayments {
    id
    number
    firstName
    lastName
    phoneNumber
    amount
    status
    wallet
    organization
    createdBy
    createdAt
    updatedAt
  }
}

query FetchBulkPaymentOrderById($id: String!) {
  fetchBulkPaymentOrderById(id: $id) {
    id
    label
    totalAmount
    status
    rejectedReason
    currentApprovalLevel
    createdAt
    lastRelaunchAt
    approvers {
      id
      firstName
      lastName
      position
    }
    approvals {
      level
      approvedAt
      approverId
    }
    payments {
      id
      firstName
      lastName
      phoneNumber
      amount
      wallet
    }
  }
}

query FetchMyBulkPaymentOrders {
  fetchMyBulkPaymentOrders {
    id
    label
    totalAmount
    status
    type
    approvers {
      id
      firstName
      lastName
    }
    createdAt
  }
}
