name: Build and Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.2.0

      - name: Install dependencies
        run: npm install

      - name: Build (dev)
        if: github.ref == 'refs/heads/dev'
        run: |
          NODE_OPTIONS=--max-old-space-size=4096 npm run build:dev

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.MOSSALL_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MOSSALL_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3 and CloudFront (dev)
        if: github.ref == 'refs/heads/dev'
        run: |
          aws configure list
          aws s3 sync --acl public-read --delete dist/mossal-web-app s3://mossall-web-dev
          aws cloudfront create-invalidation --distribution-id E1WXRVLGIQ225S --paths '/*'

